"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# -----------------------------------------------------------------------------
# BASE_DIR: Defines the base directory of the project.
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# SECURITY
# -----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-24qkug!kfw5r0z$hxxmm(vpe!j^jp1b#q*lw%1%oe5e$b8be!8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # Adjust to include your production hostnames

# -----------------------------------------------------------------------------
# APPLICATION DEFINITION
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Default Django apps:
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps:
    'rest_framework',

    # Custom applications:
    'maritime',  # Original maritime vessel tracking (can be re-enabled later)
    'weather',   # New weather app for marine weather data
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Templates configuration: Looks for templates in app directories and any specified DIRS.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add global template paths here if needed.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# -----------------------------------------------------------------------------
# DATABASE CONFIGURATION
# -----------------------------------------------------------------------------
# Here we define multiple databases: a default database and separate databases
# for the maritime and weather apps. The values are sourced from environment variables,
# with fallback defaults if not provided.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DEFAULT_DB', 'default_db'),
        'USER': os.environ.get('POSTGRES_USER', 'default_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'default_pass'),
        'HOST': os.environ.get('DB_HOST', 'db'),  # 'db' corresponds to the Postgres container in docker-compose.
        'PORT': '5432',
    },
    'maritime': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('MARITIME_DB', 'maritime_db'),
        'USER': os.environ.get('POSTGRES_USER', 'maritime_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'maritime_pass'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': '5432',
    },
    'weather': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('WEATHER_DB', 'weather_db'),
        'USER': os.environ.get('POSTGRES_USER', 'weather_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'weather_pass'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': '5432',
    },
}

# -----------------------------------------------------------------------------
# DATABASE ROUTERS
# -----------------------------------------------------------------------------
# Django uses these router classes to direct database read and write operations.
# For example, the MaritimeRouter should route all operations for models in the
# maritime app to the 'maritime' database, and the WeatherRouter routes weather app
# models to the 'weather' database.
DATABASE_ROUTERS = [
    'core.db_routers.MaritimeRouter',
    'core.db_routers.WeatherRouter',
]

# -----------------------------------------------------------------------------
# CELERY CONFIGURATION
# -----------------------------------------------------------------------------
# Celery uses Redis as the broker and result backend. Task events are enabled for monitoring.
CELERY_BROKER_URL = f"redis://{os.environ.get('REDIS_HOST', 'redis')}:6379/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_SEND_SENT_EVENT = True

# -----------------------------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -----------------------------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# WEATHER SETTINGS
# -----------------------------------------------------------------------------
# Coordinates for the marine weather API. Adjust these as needed or make them dynamic.
WEATHER_LATITUDE = 54.544587
WEATHER_LONGITUDE = 10.227487

# -----------------------------------------------------------------------------
# STATIC FILES (CSS, JavaScript, Images)
# -----------------------------------------------------------------------------
STATIC_URL = 'static/'

# -----------------------------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
